### ISSUE TITLE
Error: 'NoneType' object has no attribute 'eval' on Google Colab

### ISSUE THREAD

**Issue by vesvese55x** [medahmedkrichen/ViDubb-AI-Video-Dubbing#3]
"First of all, thank you for your hard work; you've created something very beautiful and useful. When I run it on Google Colab, it shows the error in the image. It's not processing. What could be the reason?"

![image](https://github.com/user-attachments/assets/1e1dad5b-ae71-439f-b5ad-e00c3ef344a7)

**Comment by medahmedkrichen** [comment]
Hi!
Thank you for your kind words!

make sure to add your hugging face access token into the "new_token ='' " from [Hugging Face](https://huggingface.co/settings/tokens) and make sure to request access to [pyannote/speaker-diarization-3.1](https://huggingface.co/pyannote/speaker-diarization-3.1).

```
# Update the HF_TOKEN value (required)
env_file_path = 'ViDubb/.env'
with open(env_file_path, 'r') as file:
    lines = file.readlines()


new_token = ""
for i, line in enumerate(lines):
    if line.startswith('HF_TOKEN'):
        lines[i] = f'HF_TOKEN={new_token}\n'

# Write the updated lines back to the .env file
with open(env_file_path, 'w') as file:
    file.writelines(lines)
```

I also added the possibility of opening Gradio in a public website.

**Comment by harry2141985** [comment]
which file?
